dist: xenial
os: linux
language: php

php:
    - 7.3
    - 7.4
    - 8.0
    - nightly
cache:
    directories:
        - $HOME/.composer/cache

jobs:
    include:
        -   php: 7.3
            env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    fast_finish: true
    allow_failures:
        -   php: nightly

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit
